# This workflow will:
# - install Python dependencies
# - check linting and formatting
# - run tests
# - check code coverage

name: pytests

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths: ["src/*.py", "tests/*.py"]
  pull_request:
    paths: ["src/*.py", "tests/*.py"]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Check formatting
        run: |
          uv run --no-sync ruff check --output-format=github
          uv run --no-sync ruff format --check

      - name: Run tests
        run: uv run --no-sync pytest tests

      - name: Check coverage
        run: uv run --no-sync coverage report --fail-under 90
